#!/usr/bin/env bash
# One-command production install: Docker stack + Nginx + Redis + PocketBase + developer user.
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Majid-Tayebi/Hoomban/main/scripts/install.sh | bash
#   # or from a cloned repo:
#   bash scripts/install.sh
set -euo pipefail

REPO_URL="${HOOMBAN_REPO_URL:-https://github.com/Majid-Tayebi/Hoomban.git}"
INSTALL_DIR="${HOOMBAN_INSTALL_DIR:-$(pwd)/Hoomban}"
BRANCH="${HOOMBAN_BRANCH:-main}"

rand_hex() {
	openssl rand -hex "${1:-16}" 2>/dev/null || head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
}

detect_host() {
	if [ -n "${SERVER_HOST:-}" ]; then
		echo "$SERVER_HOST"
		return
	fi
	# Prefer the machine's primary NIC IP (api.ipify can return a wrong egress IP).
	local ip
	ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
	if [ -n "$ip" ] && [ "$ip" != "127.0.0.1" ]; then
		echo "$ip"
		return
	fi
	ip="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || true)"
	echo "${ip:-127.0.0.1}"
}

ensure_docker() {
	if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
		return 0
	fi
	if command -v docker >/dev/null 2>&1 && ! docker info >/dev/null 2>&1; then
		if command -v systemctl >/dev/null 2>&1; then
			systemctl start docker 2>/dev/null || true
		fi
		if ! docker info >/dev/null 2>&1; then
			nohup dockerd >/tmp/hoomban-dockerd.log 2>&1 &
			for _ in $(seq 1 30); do
				docker info >/dev/null 2>&1 && break
				sleep 1
			done
		fi
	fi
	if ! command -v docker >/dev/null 2>&1; then
		echo "Docker not found. Install Docker first, then re-run this script."
		exit 1
	fi
	if ! docker info >/dev/null 2>&1; then
		echo "Docker daemon is not running. Start dockerd and re-run."
		exit 1
	fi
}

clone_or_update() {
	if [ -f "docker-compose.yml" ]; then
		INSTALL_DIR="$(pwd)"
		echo "==> Using current directory $INSTALL_DIR"
		return
	fi
	if [ -f "$INSTALL_DIR/docker-compose.yml" ]; then
		echo "==> Using existing project at $INSTALL_DIR"
		cd "$INSTALL_DIR"
		if [ -d .git ]; then
			git pull --ff-only origin "$BRANCH" 2>/dev/null || true
		fi
		return
	fi
	echo "==> Cloning $REPO_URL -> $INSTALL_DIR"
	git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
	cd "$INSTALL_DIR"
}

write_env() {
	local host="$1"
	local admin_pass="${POCKETBASE_ADMIN_PASSWORD:-$(rand_hex 12)}"
	local dev_pass="${DEVELOPER_PASSWORD:-$(rand_hex 10)}"
	local cron_secret="${CRON_SECRET:-$(rand_hex 24)}"

	if [ -f .env ] && grep -q '^DEVELOPER_PASSWORD=' .env; then
		dev_pass="$(grep '^DEVELOPER_PASSWORD=' .env | cut -d= -f2-)"
	fi

	cat > .env <<EOF
# Generated by scripts/install.sh — do not commit
SERVER_HOST=${host}
POCKETBASE_URL=http://pocketbase:8090
PUBLIC_POCKETBASE_URL=http://${host}:8090
POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL:-admin@hoomban.ir}
POCKETBASE_ADMIN_PASSWORD=${admin_pass}

DEVELOPER_USERNAME=${DEVELOPER_USERNAME:-developer}
DEVELOPER_PASSWORD=${dev_pass}
DEVELOPER_NAME=${DEVELOPER_NAME:-Developer}
DEVELOPER_MOBILE=${DEVELOPER_MOBILE:-09120000099}
DEVELOPER_EMAIL=${DEVELOPER_EMAIL:-developer@hoomban.local}

VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_SUBJECT=mailto:admin@hoomban.ir

CRON_SECRET=${cron_secret}

ZARINPAL_MERCHANT_ID=
ZARINPAL_SANDBOX=true
PUBLIC_APP_URL=http://${host}

REDIS_URL=redis://redis:6379
TRUST_PROXY=true
COOKIE_SECURE=false
ORIGIN=http://${host}
NODE_ENV=production
EOF

	echo "$dev_pass" > .developer-password
	chmod 600 .env .developer-password 2>/dev/null || true
}

wait_healthy() {
	local service="$1"
	local tries="${2:-60}"
	for _ in $(seq 1 "$tries"); do
		local health
		health="$(docker compose ps "$service" --format '{{.Health}}' 2>/dev/null || true)"
		if [ "$health" = "healthy" ]; then
			return 0
		fi
		sleep 2
	done
	return 1
}

main() {
	ensure_docker
	clone_or_update

	local host
	host="$(detect_host)"
	echo "==> Server host: $host"

	if [ ! -f .env ]; then
		write_env "$host"
	else
		# Keep secrets, refresh public URLs for current host
		if ! grep -q '^DEVELOPER_PASSWORD=' .env; then
			echo "DEVELOPER_PASSWORD=$(rand_hex 10)" >> .env
		fi
		if ! grep -q '^DEVELOPER_USERNAME=' .env; then
			echo "DEVELOPER_USERNAME=developer" >> .env
		fi
		sed -i "s|^SERVER_HOST=.*|SERVER_HOST=${host}|" .env 2>/dev/null || true
		sed -i "s|^PUBLIC_APP_URL=.*|PUBLIC_APP_URL=http://${host}|" .env 2>/dev/null || true
		sed -i "s|^PUBLIC_POCKETBASE_URL=.*|PUBLIC_POCKETBASE_URL=http://${host}:8090|" .env 2>/dev/null || true
		sed -i "s|^ORIGIN=.*|ORIGIN=http://${host}|" .env 2>/dev/null || true
		sed -i 's|^TRUST_PROXY=.*|TRUST_PROXY=true|' .env 2>/dev/null || true
	fi

	# shellcheck disable=SC1091
	set -a && source .env && set +a

	echo "==> Building and starting stack (nginx + app + pocketbase + redis)..."
	docker compose up -d --build

	echo "==> Waiting for PocketBase..."
	wait_healthy pocketbase 90

	echo "==> Bootstrapping developer user..."
	docker compose --profile bootstrap run --rm bootstrap

	echo ""
	echo "=============================================="
	echo "  Hoomban is running"
	echo "=============================================="
	echo "  Site:        http://${host}/"
	echo "  PocketBase:  http://${host}:8090/_/"
	echo ""
	echo "  Login (username + password):"
	echo "    Username:  ${DEVELOPER_USERNAME:-developer}"
	echo "    Password:  $(grep '^DEVELOPER_PASSWORD=' .env | cut -d= -f2-)"
	echo ""
	echo "  Manage: cd $INSTALL_DIR && docker compose ps"
	echo "=============================================="
}

main "$@"
